Repository NTOU-Order-Now/Order-Now-Frontend, pull requests merged in 2025-01, with the labels that each got.

#163 134 integrate websocket
  public/newOrderNotify.mp3
  src/components/common/ActiveNotifyDialog.jsx
  src/components/merchantPage/dishOptions/AddToCart.jsx
  src/components/storePage/management/order/UnacceptedList.jsx
  src/context/WebSocketContextProvider.jsx
  src/hooks/cart/useCartAddMutation.jsx
  src/hooks/cart/useCartSendMutation.jsx
  src/hooks/cart/useCartUpdateMutation.jsx
  src/pages/store/Order.jsx
Labels: enhancement

#165 99 change not login users sidebar state
  src/App.jsx
  src/components/homePage/Sidebar.jsx
  src/components/storePage/home/Sidebar.jsx
  src/pages/HistoryOrders.jsx
  src/pages/Home.jsx
  src/pages/MerchantRegister.jsx
  src/pages/store/Home.jsx
Labels: enhancement

#166 140 fix merchant menu management page image not show bug
  src/api/image/postImage.js
  src/api/pos/setting/getStoreInfo.js
  src/components/storePage/management/menu/MenuItemCard.jsx
  src/components/storePage/management/menu/MenuSection.jsx
  src/components/storePage/management/menu/editPage/DishEdit.jsx
  src/components/storePage/management/menu/editPage/DishForm.jsx
  src/components/storePage/management/menu/editPage/EditHeader.jsx
  src/components/storePage/settings/StoreForm.jsx
  src/hooks/image/useImageUploadMutation.jsx
  src/hooks/store/useCreateDishMutation.jsx
  src/pages/store/Home.jsx
  src/pages/store/Menu.jsx
Labels: bug, enhancement

#167 fixed by check path name and endpoint
  src/components/homePage/Sidebar.jsx
  src/components/homePage/SidebarButton.jsx
  src/components/storePage/home/Sidebar.jsx
Labels: enhancement

#162 Fixed userName truncate
  src/components/homePage/Sidebar.jsx
Labels: enhancement

#161 Develop/scrolling bugs
  package-lock.json
  src/App.jsx
  src/pages/LoginRegister.jsx
  vite.config.js.timestamp-1735747529426-8e4d0cecd08f6.mjs
Labels: bug, enhancement

#147 Update MenuInfo.jsx
  src/components/merchantPage/MenuHeader.jsx
  src/components/merchantPage/MenuInfo.jsx
  src/components/merchantPage/MenuInfoDrawer.jsx
Labels: enhancement

#169 Integrate/review number api
  src/api/review/getReviewClient.js
  src/api/review/getReviewNumber.js
  src/components/reviewPage/RatingBar.jsx
  src/hooks/menu/useCategoryListQuery.jsx
  src/hooks/review/useReviewNumberQuery.jsx
  src/pages/Review.jsx
Labels: enhancement

#170 delete justify center and min-h-screen
  src/components/merchantPage/MenuSection.jsx
Labels: enhancement

#171 Rectify/home page scroll bug
  src/components/merchantPage/MerchantCard.jsx
  src/components/merchantPage/MerchantList.jsx
  src/pages/Home.jsx
  src/pages/store/Dashboard.jsx
  src/skeleton/merchant/MerchantCardSkeleton.jsx
  src/skeleton/merchant/MerchantSkeleton.jsx
Labels: bug, enhancement

#175 add keydown
  src/components/authPage/LoginForm.jsx
Labels: bug

#176 Fix/tiny bugs
  src/components/authPage/LoginForm.jsx
  src/components/common/ActiveNotifyDialog.jsx
  src/components/homePage/Sidebar.jsx
  src/components/homePage/SidebarButton.jsx
  src/components/storePage/home/Sidebar.jsx
  src/context/WebSocketContextProvider.jsx
  src/pages/store/Order.jsx
Labels: bug

#177 fixed
  src/components/common/ActiveNotifyDialog.jsx
  src/hooks/loginRegisterPage/useRegisterMutation.jsx
  src/pages/store/Order.jsx
Labels: bug

#178 delete unnecessary skeleton
  src/components/storePage/management/menu/MenuSection.jsx
  src/hooks/store/useCategoryNameMutation.jsx
  src/pages/store/Menu.jsx
Labels: enhancement

#181 add google icon svg
  src/assets/GoogleIcon.jsx
  src/components/authPage/LoginForm.jsx
Labels: enhancement

#184 fix cart send socket no notify bug
  src/context/WebSocketContextProvider.jsx
  src/pages/store/Order.jsx
Labels: bug, enhancement

#188 change to MerchantCardSkeleton
  src/components/merchantPage/MerchantList.jsx
Labels: enhancement
